

modLoader="javafml" #mandatory


loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.


license="All rights reserved"


issueTrackerURL="http://my.issue.tracker/" #optional


[[mods]] #mandatory


modId="botsmod" #mandatory


version="${file.jarVersion}" #mandatory
 

displayName="Bane Of The Souls" #mandatory


displayURL="http://example.com/" #optional


logoFile="examplemod.png" #optional


credits="Creator: Th3Fr3ak , " #optional


authors="Th3Fr3ak" #optional


description='''
Bane Of The Souls yes.... A long time ago the nether was a beneath world , a world only populated by many greenish feature , same complexity as the 'Overworld' just sometime a little bit more twisted , That twist was caused by 3 primal Crystals mainly called by the name ('(Delta, Eldritch, Heat)'Those are called primordial crystal cause they were the first, and so same as the plant , they evolved)
                          Every form of life on this Strange place was evolved to be able to live in those caverns, some emitted light, some hided from the light , and well some denied the light.
                          Those many forms of evolution leaded to a new type of Fauna and Flora, many concept were created by many evolved forms of life , At this point they were more evolved then a current villager or player , in their own ways .
                          But this verdish place , took a bad turn , many forms of life empty their souls and banished them, to gain more power over some, forcing them to do the same, rare were the survivors , they just evolved in their new hellish environment and became many of the creatures we see in the nether now .

                          Good thing tho since i made that the player can go back to the old dimension now called The Banned Lands
                          With the help of the time Goddess Krasía (Pronunciation: [Kræshïa]) , you'll be able to know how to achieve this journey to The Banned Lands, defeating the gate keeper and creating a way to The Banned Lands to find out what this new dimension can offer you .


'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.botsmod]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[31,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.botsmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"
